# Generated by Django 4.1.3 on 2022-11-29 03:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bancoorigem', models.CharField(max_length=100)),
                ('agenciaorigem', models.CharField(max_length=100)),
                ('contaorigem', models.CharField(max_length=100)),
                ('bancodestino', models.CharField(max_length=100)),
                ('agenciadestino', models.CharField(max_length=100)),
                ('contadestino', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField(default=datetime.datetime.now)),
            ],
        ),
    ]
