# Generated by Django 4.1.3 on 2022-11-29 13:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_transacao_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='impor',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
